import type { APIRoute } from "astro";
import { getCollection } from "astro:content";

/**
 * /llms.txt — Cloudflare AI agents / LLM-readable site index.
 *
 * Follows the emerging llms.txt convention so AI assistants can discover
 * this site's content. Each post's markdown URL is listed alongside its
 * human-readable URL.
 */
export const GET: APIRoute = async () => {
	const posts = (await getCollection("posts")).sort(
		(a: any, b: any) => new Date(b.data.date).getTime() - new Date(a.data.date).getTime(),
	);

	const lines: string[] = [
		"# NBA Blog",
		"",
		"> Data-driven NBA analysis with interactive statistical visualizations.",
		"> Powered by NBA Blog Studio — an AI-native blogging platform built on Cloudflare.",
		"",
		"## Posts",
		"",
	];

	for (const post of posts) {
		const desc = post.data.description
			? ` — ${post.data.description}`
			: post.data.tags.length > 0
				? ` — ${post.data.tags.join(", ")}`
				: "";
		lines.push(`- [${post.data.title}](/posts/${post.slug})${desc}`);
		lines.push(`  Markdown (AI-readable): /posts/${post.slug}.md`);
		lines.push("");
	}

	lines.push(
		"## About",
		"",
		"This blog is generated by the NBA Blog Studio MCP server.",
		"Connect to the MCP server from Claude Desktop or any MCP-compatible client",
		"to author new data-rich NBA posts with interactive visualization components.",
		"",
		"## Markdown Endpoints",
		"",
		"Every post is available as structured markdown optimised for AI assistants:",
		"- `/posts/{slug}.md` — Full article with statistics formatted as tables and ASCII bar charts",
		"- `/llms.txt` — This file",
		"",
	);

	return new Response(lines.join("\n"), {
		headers: { "Content-Type": "text/plain; charset=utf-8" },
	});
};
