// AUTO-GENERATED — do not edit by hand.
// Run `npm run build:ui` to regenerate.
// This is a placeholder for development. The real content is generated by scripts/embed-html.mjs
export const blogPreviewHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>NBA Blog Preview</title>
</head>
<body>
  <div id="root">
    <p style="color:#94a3b8;text-align:center;padding:36px">
      Preview not built yet. Run <code>npm run build:ui</code> to generate.
    </p>
  </div>
</body>
</html>`;
